[package]
name = "rs-pyextend"
version = "0.1.0"
authors = ["roko@summer <roko.mislov.m@gmail.com>"]
cargo-features = ["nightly"]

[lib]
name = "libpyextend"
crate-type = ["cdylib"]

[dependencies]
webbrowser = "0.4.0"

[dependencies.cpython]
version = "0.2"
features = ["extension-module"]